/*
 * Name         DataBase_describe.h
 * Author       Maksim Golikov (SW developer)
 * Created      19 FEB 2018
 * Description  file for describe Data base field (header file)
 */

#ifndef COMMON_DATABASE_DATABASE_DESCRIBE_H_
#define COMMON_DATABASE_DATABASE_DESCRIBE_H_



typedef enum{
	ID,
	COLOR,
	INVULNERABILITY_TIME,
	HEALTH,
	HEADBAND_VIBRO_TIME,
	SHOCK_TIME,
	SOUND_VOLUME,
	FRIENDLY_FIRE,
//===STATISTIC
	RESPOWNS_NUMBER,
	KILLS_NUMBER,
	MEDICINE_NUMBER,
	FEADBACK_SHOTS_NUMBER,
	FEADBACK_KILLS_NUMBER,
	SHOTS_NUMBER,
	SHOTS_FROM_COUNT,
	DAMAGE_FROM_COUNT,
	KILLS_WHO_COUNT,
//====TOMMY GUN
	DAMAGE_TOMMY_GUN,
	IR_STRENGTH_TOMMY_GUN,
	FIRE_RATE_TOMMY_GUN,
	SHOTS_IN_AUTOMOD_TOMMY_GUN,
	CLIPS_NUMBER_TOMMY_GUN,
	AMMO_NUMBER_TOMMY_GUN,
	AUTORESPOUN_TIME_TOMMY_GUN,
//===============================
	FINISH_FLASH,
//=====GAME
	GAME_MODE,

	DB_field_Amount
}DB_Field_t;





#endif /* COMMON_DATABASE_DATABASE_DESCRIBE_H_ */
